input CreateListInput {
	name: String!
	type: ListType!
}

input InsertListItemInput {
	listId: ID!
	name: String!
}

input DeleteListItemInput {
	itemId: ID!
}

input DeleteListItemsInput {
	itemIds: [ID!]!
}

input DeleteListInput {
	listId: ID!
}

type ListItem {
	id: ID!
	name: String!
}

enum ListType {
	pick
	list
}

type List {
	id: ID!
	name: String!
	type: ListType!
	items: [ListItem!]!
}

type Mutation {
	createNewList(input: CreateListInput!): List!
	insertListItem(input: InsertListItemInput!): ListItem!
	deleteListItem(input: DeleteListItemInput!): Boolean!
	deleteListItems(input: DeleteListItemsInput!): Int!
	deleteList(input: DeleteListInput!): Boolean!
}

type Query {
	lists: [List!]!
	list(id: ID!): List
}
